Description: EC2 Redash
Parameters:
  KeyName:
    Description: 'Key name to ssh into instance'
    Type: String
  InstanceType:
    Description: 'Instance Type'
    Type: String
    Default: t3a.small
  NameTag:
    Description: 'Instance Name'
    Type: String
    Default: Redash
  SetupIp:
    Description: 'Restrict Security groups to this IP in first Setup'
    Type: String

Resources:
  EC2Instance:
    Properties:
      ImageId: ami-046c6a0123bf94619
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SG
      Tags:
        - Key: Name
          Value: !Ref NameTag
    Type: 'AWS::EC2::Instance'
  SG:
    Properties:
      GroupDescription: shh, http, https traffic allowed
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: !Ref SetupIp
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: !Ref SetupIp
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
    Type: 'AWS::EC2::SecurityGroup'
